spring.application.name=blog
# PostgreSQL Database (Aiven.io)
spring.datasource.url=jdbc:postgresql://dpg-cumo305umphs738l9f0g-a.oregon-postgres.render.com:5432/blogdb_ojfu
spring.datasource.username=suvetha
spring.datasource.password=jQnIaxSnTQz0Qx6YW9gnSIRl7rMH1CKm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret Key
app.jwt.secret=A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6
app.jwt.expiration=86400000
